[package]
name = "imgtool"
version = "0.1.0"
authors = ["gl_chain@163.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.19.0"