[package]
name = "imgtool"
version = "0.1.0"
authors = ["gl_chain@163.com"]
edition = "2021"
readme = "README.md"

[[bench]]
name = "fibonacci"
harness = false

[dependencies]
image = "0.25.1"
criterion = "0.5.1"